.PHONY: all clean

CC=gcc
CFLAGS+=
LDFLAGS+=-lm     # link to math library

TARGET=test_hmm test train

all: $(TARGET)
# type make/make all to compile test_hmm

clean:
	$(RM) $(TARGET)   # type make clean to remove the compiled file
